main:
	g++ -o GameOfLife src/GameOfLife.cc src/Cell.cc src/Lattice.cc src/CellVector.cc src/CellMatrix.cc src/Tools.cc src/State.cc
test:
	g++ -o test src/test.cc src/Cell.cc src/Lattice.cc src/CellVector.cc src/CellMatrix.cc src/Tools.cc src/State.cc
clean: 
	rm -f *.o
vanish:
	rm GameOfLife
vanish-test:
	rm test
